name: deployment workflow
on: workflow_dispatch
jobs: 
    build_job:
          runs-on: ubuntu-latest
          steps:
             - name: Checkout code          # Actions-checkout is used to fetch your repository's code onto the runner machine
               uses: actions/checkout@v3
             - name: Configure AWS credentials
               uses: aws-actions/configure-aws-credentials@v2
               with:
                 aws-access-key-id: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
                 aws-secret-access-key: ${{secrets.AWS_S3_SECRET_ACCESS_KEY}}
                 aws-region: ap-south-1

